export const accountConstants = {
    GET_ACCOUNT_REQUEST: 'GET_ACCOUNT_REQUEST',
    GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
    GET_ACCOUNT_FAILURE: 'GET_ACCOUNT_FAILURE',

    CREATE_SAVING_ACCOUNT_REQUEST: 'CREATE_SAVING_ACCOUNT_REQUEST',
    CREATE_SAVING_ACCOUNT_SUCCESS: 'CREATE_SAVING_ACCOUNT_SUCCESS',
    CREATE_SAVING_ACCOUNT_FAILURE: 'CREATE_SAVING_ACCOUNT_FAILURE',
}