export const accountConstants = {
    GET_ACCOUNT_REQUEST: 'GET_ACCOUNT_REQUEST',
    GET_ACCOUNT_SUCCESS: 'GET_ACCOUNT_SUCCESS',
    GET_ACCOUNT_FAILURE: 'GET_ACCOUNT_FAILURE',

    CREATE_SAVING_ACCOUNT_REQUEST: 'CREATE_SAVING_ACCOUNT_REQUEST',
    CREATE_SAVING_ACCOUNT_SUCCESS: 'CREATE_SAVING_ACCOUNT_SUCCESS',
    CREATE_SAVING_ACCOUNT_FAILURE: 'CREATE_SAVING_ACCOUNT_FAILURE',

    DELETE_SAVING_ACCOUNT_REQUEST: 'DELETE_SAVING_ACCOUNT_REQUEST',
    DELETE_SAVING_ACCOUNT_SUCCESS: 'DELETE_SAVING_ACCOUNT_SUCCESS',
    DELETE_SAVING_ACCOUNT_FAILURE: 'DELETE_SAVING_ACCOUNT_FAILURE',

    UPDATE_SAVING_ACCOUNT_REQUEST: 'UPDATE_SAVING_ACCOUNT_REQUEST',
    UPDATE_SAVING_ACCOUNT_SUCCESS: 'UPDATE_SAVING_ACCOUNT_SUCCESS',
    UPDATE_SAVING_ACCOUNT_FAILURE: 'UPDATE_SAVING_ACCOUNT_FAILURE',
}