export const friendConstants = {
    GET_FRIEND_SUCCESS: 'GET_FRIEND_SUCCESS',
    GET_FRIEND_FAILURE: 'GET_FRIEND_FAILURE',

    CREATE_FRIEND_SUCCESS: 'CREATE_FRIEND_SUCCESS',
    CREATE_FRIEND_FAILURE: 'CREATE_FRIEND_FAILURE',
}