export const notiConstants = {
    GET_NOTI_SUCCESS: 'GET_NOTI_SUCCESS',
    GET_NOTI_FAILURE: 'GET_NOTI_FAILURE',

    CREATE_NOTI_SUCCESS: 'CREATE_NOTI_SUCCESS',
    CREATE_NOTI_FAILURE: 'CREATE_NOTI_FAILURE',
}