export const transactionConstants = {
    CREATE_TRANSACTION_SUCCESS: 'CREATE_TRANSACTION_SUCCESS',
    CREATE_TRANSACTION_FAILURE: 'CREATE_TRANSACTION_FAILURE',

    GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
    GET_TRANSACTION_FAILURE: 'GET_TRANSACTION_FAILURE',

    GET_AS_TRANSACTION_SUCCESS: 'GET_AS_TRANSACTION_SUCCESS',
    GET_AS_TRANSACTION_FAILURE: 'GET_AS_TRANSACTION_FAILURE',
}